	.segment "ZEROPAGE"
	.exportzp _sp0, _sp1, _fp0, _fp1
	.exportzp _r0, _r1, _r2, _r3, _r4, _r5, _r6, _r7
	.exportzp _s0, _s1, _s2, _s3, _s4, _s5, _s6, _s7
	.exportzp _tmp0, _tmp1
_sp0:	.byte 0
_sp1:	.byte 0
_fp0:	.byte 0
_fp1:	.byte 0
_r0:	.byte 0
_r1:	.byte 0
_r2:	.byte 0
_r3:	.byte 0
_r4:	.byte 0
_r5:	.byte 0
_r6:	.byte 0
_r7:	.byte 0
_s0:	.byte 0
_s1:	.byte 0
_s2:	.byte 0
_s3:	.byte 0
_s4:	.byte 0
_s5:	.byte 0
_s6:	.byte 0
_s7:	.byte 0
_tmp0:	.byte 0
_tmp1:	.byte 0
