	.segment "ZEROPAGE"
	.exportzp _sp0, _sp1, _fp0, _fp1
	.exportzp _r0, _r1, _r2, _r3, _r4, _r5, _r6, _r7
	.exportzp _s0, _s1, _s2, _s3, _s4, _s5, _s6, _s7
	.exportzp _e0,  _e1,  _e2,  _e3,  _e4,  _e5,  _e6,  _e7
	.exportzp _e8,  _e9,  _e10, _e11, _e12, _e13, _e14, _e15
	.exportzp _e16, _e17, _e18, _e19, _e20, _e21, _e22, _e23
	.exportzp _e24, _e25, _e26, _e27, _e28, _e29, _e30, _e31
	.exportzp _tmp0, _tmp1
_sp0:	.byte 0
_sp1:	.byte 0
_fp0:	.byte 0
_fp1:	.byte 0
_r0:	.byte 0
_r1:	.byte 0
_r2:	.byte 0
_r3:	.byte 0
_r4:	.byte 0
_r5:	.byte 0
_r6:	.byte 0
_r7:	.byte 0
_s0:	.byte 0
_s1:	.byte 0
_s2:	.byte 0
_s3:	.byte 0
_s4:	.byte 0
_s5:	.byte 0
_s6:	.byte 0
_s7:	.byte 0
_e0:	.byte 0
_e1:	.byte 0
_e2:	.byte 0
_e3:	.byte 0
_e4:	.byte 0
_e5:	.byte 0
_e6:	.byte 0
_e7:	.byte 0
_e8:	.byte 0
_e9:	.byte 0
_e10:	.byte 0
_e11:	.byte 0
_e12:	.byte 0
_e13:	.byte 0
_e14:	.byte 0
_e15:	.byte 0
_e16:	.byte 0
_e17:	.byte 0
_e18:	.byte 0
_e19:	.byte 0
_e20:	.byte 0
_e21:	.byte 0
_e22:	.byte 0
_e23:	.byte 0
_e24:	.byte 0
_e25:	.byte 0
_e26:	.byte 0
_e27:	.byte 0
_e28:	.byte 0
_e29:	.byte 0
_e30:	.byte 0
_e31:	.byte 0
_tmp0:	.byte 0
_tmp1:	.byte 0
